site_name: DanSpeech
theme: readthedocs
site_description: 'An open-source Danish speech recognition tool'
use_directory_urls: False
site_dir: ../docs
markdown_extensions:
- mdx_math:
    enable_dollar_delimiter: True #for use of inline $..$
- admonition
- codehilite
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML']
extra_css: [extra.css]


nav:
  - Home: index.md
  - Installation: installing.md
  - Usage: usage.md
  - Recognizer: recognizer.md
  - Audio Sources: audio.md
  - Pre-trained models: models.md
  - Pre-trained language models: lms.md
